client_id: <DATABASE.COM CONSUMER KEY HERE>
client_secret: <DATABASE.COM CONSUMER SECRET HERE>
username: <YOUR DATABASE.COM LOGIN USERNAME>
password: <YOUR DATABASE.COM LOGIN PASSWORD APPENDED TO YOUR SECURITY TOKEN>
host: login.salesforce.com
debugging: true