client_id: 3MVG9y6x0357HleexrZb5pIO637KDmLe2oP6unrEicuwZi2Tdmuk1FIjOIJ36HcvDuKaW8vlp5DqZc6s5Jf9K
client_secret: 8203035346345245334
username: herokubook@database.com
password: welcome99Hi3eH3Uz3gDy4Mhexnd0ItlW
host: login.salesforce.com
debugging: true